site_name: Team 11 - Meno-Time
site_url: https://team11.com
nav:
  - Home: index.md
  - Login: login.md
  - Register: register.md
  - Delete: delete.md
  - InputOutputFlashCards: inputOutputFlashCards.md
  - Share Flash Card: shareFlashcard.md
  - RenderNotes: rendernotes.md
  - Share Notes: sharenotes.md
  - To-do List: todolist.md
  - Pomodoro Timer: pomodorotimer.md
  - Track Hour: trackHours.md
theme: readthedocs
